apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: ghost-protocol-latency
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - staging-app
  delay:
    latency: '2000ms'
    correlation: '50'
    jitter: '100ms'
  duration: '15m'
  scheduler:
    cron: '@every 10m'